// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWj2IkH-mRL_PmLj8cBEHToHqOJZLBwE',
    appId: '1:689369465246:android:c8ade2c02ba3a07c85568f',
    messagingSenderId: '689369465246',
    projectId: 'shopping-list-app-f1fbe',
    storageBucket: 'shopping-list-app-f1fbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRepbjUdyLwzUPefczZKtHAfUhxjagFtY',
    appId: '1:689369465246:ios:6e8074a67f7e5d7f85568f',
    messagingSenderId: '689369465246',
    projectId: 'shopping-list-app-f1fbe',
    storageBucket: 'shopping-list-app-f1fbe.appspot.com',
    androidClientId: '689369465246-4l5d2v59ba9nvn4evru9jg7i028kbjfo.apps.googleusercontent.com',
    iosClientId: '689369465246-13oornr6cfrbnr1irp9nm0kpafbg8jhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingListApp',
  );
}
